config/routes.rb
Rails.application.routes.draw do

  root :to => "visitors#index"
  
  resources :subtopics do
    resources :examples
    resources :proofs    
  end

  resources :courses do
    resources :topics
  end

  devise_for :users
  resources :users
end

app/models/subtopic.rb
class Subtopic < ActiveRecord::Base
  belongs_to :topic

  has_many :proofs
  has_many :examples
end

app/controllers/subtopics_controller.rb
class SubtopicsController < ApplicationController

=begin
  
  Subtopics controller is a child of the topics controller, but to avoid
  excessive nesting (because the topics controller is a child of the 
  course model), subtopics will not be routes nested under topics.
  
  Instead, the subtopics controller will be related to the topics controller
  through manual assignments of the topic


=end

  before_action :set_subtopic, only: [:show, :edit, :update, :destroy]

  def index
    @subtopics = Subtopic.all
  end

  # GET /subtopics/1
  # GET /subtopics/1.json
  def show
    @subtopic = Subtopic.find(params[:id])
    @topic = Topic.find(@subtopic.topic_id)
    @proofs = @subtopic.proofs
    @examples = @subtopic.examples
  end

  # GET /subtopics/new
  def new
    @subtopic = Subtopic.new
  end

  # GET /subtopics/1/edit
  def edit
  end

  # POST /subtopics
  # POST /subtopics.json
  def create
    @subtopic = Subtopic.new(subtopic_params)

    respond_to do |format|
      if @subtopic.save
        format.html { redirect_to @subtopic, notice: 'Subtopic was successfully created.' }
        format.json { render :show, status: :created, location: @subtopic }
      else
        format.html { render :new }
        format.json { render json: @subtopic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtopics/1
  # PATCH/PUT /subtopics/1.json
  def update
    respond_to do |format|
      if @subtopic.update(subtopic_params)
        format.html { redirect_to @subtopic, notice: 'Subtopic was successfully updated.' }
        format.json { render :show, status: :ok, location: @subtopic }
      else
        format.html { render :edit }
        format.json { render json: @subtopic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtopics/1
  # DELETE /subtopics/1.json
  def destroy
    @subtopic.destroy
    respond_to do |format|
      format.html { redirect_to subtopics_url, notice: 'Subtopic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtopic
      @subtopic = Subtopic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtopic_params
      params.require(:subtopic).permit(:name, :description, :video_link, :proof, :example, :topic_id)
    end
end

app/helpers/subtopics_helper.rb
module SubtopicsHelper
end

app/views/subtopics/_form.html.haml
= form_for @subtopic do |f|
  - if @subtopic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subtopic.errors.count, "error")} prohibited this subtopic from being saved:"
      %ul
        - @subtopic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = render 'layouts/textbar'    
    = f.text_area :description, :id => 'wysihtml5-textarea', :class => 'input_area'
  .actions
    = f.submit 'Save'

app/views/subtopics/edit.html.haml
.row
  .large-12.columns
    %h1 Editing subtopic

    = render 'form'

    = link_to 'Show', @subtopic
    \|
    = link_to 'Back', subtopics_path

app/views/subtopics/index.html.haml
.row
  .large-12.columns
    %h1 Listing subtopics

    %table
      %tr
        %th Name
        %th Description
        %th Video link
        %th Proof
        %th Example
        %th
        %th
        %th

      - @subtopics.each do |subtopic|
        %tr
          %td= subtopic.name
          %td= subtopic.description
          %td= link_to 'Show', subtopic
          %td= link_to 'Edit', edit_subtopic_path(subtopic)
          %td= link_to 'Destroy', subtopic, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Subtopic', new_subtopic_path

app/views/subtopics/new.html.haml
.row
  .large-12.columns
    %h1 New subtopic

    = render 'form'

    = link_to 'Back', subtopics_path

app/views/subtopics/show.html.haml
.row
  .large-12.columns
    .show-info
      .center
        .sub-title.thin.grey= @topic.name
        .mid-title= @subtopic.name
        = raw @subtopic.description
      %p

.row
  .large-6.columns
    %p
      .proof
        %b Proof:
        //= raw @subtopic.proof
        - @proofs.each do |proof|
          %br=link_to proof.name, [@subtopic, proof]
        %br
        %b= link_to "All Proofs", subtopic_proofs_path(@subtopic)
        %br
        %b= link_to "Create new proof", new_subtopic_proof_path(@subtopic)
        

  .large-6.columns
    %p
      %b Example:
      - @examples.each do |example|
        %br= link_to example.name, [@subtopic, example]
      
      %br
      %b= link_to "Create new Example", new_subtopic_example_path(@subtopic)
%hr
  .row
    .large-12.columns
      = link_to 'Edit', edit_subtopic_path(@subtopic)
      \|
      = link_to 'Back', subtopics_path