config/routes.rb
Rails.application.routes.draw do

  root :to => "visitors#index"
  
  resources :subtopics do
    resources :examples
    resources :proofs    
  end

  resources :courses do
    resources :topics
  end

  devise_for :users
  resources :users
end

app/models/proof.rb
class Proof < ActiveRecord::Base
  belongs_to :subtopic

end

app/controllers/proofs_controller.rb
class ProofsController < ApplicationController

  before_action :set_proof, only: [:show, :edit, :update, :destroy]

  def index
    @subtopic = Subtopic.find(params[:subtopic_id])
    @proofs = @subtopic.proofs
  end

  # GET /proofs/1
  # GET /proofs/1.json
  def show
    @subtopic = Subtopic.find(params[:subtopic_id])
    @proof = @subtopic.proofs.find(params[:id])
  end

  # GET /proofs/new
  def new
    @subtopic = Subtopic.find(params[:subtopic_id])
    @proof = @subtopic.proofs.build
  end

  # GET /proofs/1/edit
  def edit
    @subtopic = Subtopic.find(params[:subtopic_id])
    @proof = @subtopic.proofs.find(params[:id])
  end

  # POST /proofs
  # POST /proofs.json
  def create
    @subtopic = Subtopic.find(params[:subtopic_id])
    @proof = @subtopic.proofs.build(proof_params)

    respond_to do |format|
      if @proof.save
        format.html { redirect_to [@subtopic,@proof], notice: 'Proof was successfully created.' }
        format.json { render :show, status: :created, location: @proof }
      else
        format.html { render :new }
        format.json { render json: @proof.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @subtopic = Subtopic.find(params[:subtopic_id])
    @proof = @subtopic.proofs.build(proof_params)
    
    respond_to do |format|
      if @proof.update(proof_params)
        format.html { redirect_to [@subtopic, @proof], notice: 'Proof was successfully updated.' }
        format.json { render :show, status: :ok, location: @proof }
      else
        format.html { render :edit }
        format.json { render json: @proof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proofs/1
  # DELETE /proofs/1.json
  def destroy
    @subtopic = Subtopic.find(params[:subtopic_id])
    
    @proof.destroy
    respond_to do |format|
      format.html { redirect_to subtopic_proofs_path, notice: 'Proof was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proof
      @proof = Proof.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proof_params
      params.require(:proof).permit(:name, :video_link, :content)
    end
    
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/views/proofs/_form.html.haml
= form_for ([@subtopic, @proof]) do |f|
  - if @proof.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proof.errors.count, "error")} prohibited this proof from being saved:"
      %ul
        - @proof.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :video_link
    = f.text_field :video_link
  .field
    = f.label :content
    = f.text_area :content, :class => 'input_area'
  .actions
    = f.submit 'Save'

app/views/proofs/edit.html.haml
.row
  .large-12.columns
    %h1 Editing proof

    = render 'form'

    = link_to 'Show', [@subtopic, @proof]
    \|
    = link_to 'Back', subtopic_proofs_path
    \|
    = link_to 'Destroy', [@subtopic, @proof], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/proofs/index.html.haml
.row
  .large-12.columns
    %h1 Listing proofs

    %table
      %tr
        %th Name
        %th Video link
        %th Content
        %th
        %th
        %th

      - @proofs.each do |proof|
        %tr
          %td= proof.name
          %td= proof.video_link
          %td.proof= raw proof.content
          %td= link_to 'Show', [@subtopic, proof]
          %td= link_to 'Edit', edit_subtopic_proof_path(@subtopic, proof)
          %td= link_to 'Destroy', [@subtopic, proof], :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Proof', new_subtopic_proof_path

app/views/proofs/new.html.haml
.row
  .large-12.columns
    %h1 New proof
    = render 'form'
    = link_to 'Back', subtopic_proofs_path

app/views/proofs/show.html.haml
.gallery
  .holder
    .list
      .item
        .row
          .large-12.columns
            %p
              %b Name:
              = @proof.name
              %br= link_to "Go back to parent subtopic", @subtopic
            %p
              %b Video:
              .center
                =raw YouTubeAddy.youtube_embed_url(@proof.video_link,853,480)
            %p
      .item
        .row
          .large-12.columns  
            %b Content:
            .proof
              =raw @proof.content

            = link_to 'Edit', edit_subtopic_proof_path(@subtopic, @proof)
            \|
            = link_to 'Back', subtopic_proofs_path