config/routes.rb
Rails.application.routes.draw do

  root :to => "visitors#index"
  
  resources :subtopics do
    resources :examples
    resources :proofs    
  end

  resources :courses do
    resources :topics
  end

  devise_for :users
  resources :users
end

app/models/example.rb
class Example < ActiveRecord::Base
  belongs_to :subtopic
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @subtopic = Subtopic.find(params[:subtopic_id])
    @examples = @subtopic.examples
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @subtopic = Subtopic.find(params[:subtopic_id])
    @example = @subtopic.examples.build
  end

  # GET /examples/1/edit
  def edit
    @subtopic = Subtopic.find(params[:subtopic_id])
    @example = @subtopic.examples.find(params[:id])
  end

  # POST /examples
  # POST /examples.json
  def create
    @subtopic = Subtopic.find(params[:subtopic_id])    
    @example = @subtopic.examples.build(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to [@subtopic, @example], notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    
    @subtopic = Subtopic.find(params[:subtopic_id])
    @example = @subtopic.examples.build
    
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to [@subtopic,@example], notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @subtopic = Subtopic.find(params[:subtopic_id])
    @example.destroy
    respond_to do |format|
      format.html { redirect_to subtopic_examples_path, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:name, :video_link, :content)
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.haml
= form_for ([@subtopic,@example]) do |f|
  - if @example.errors.any?
    #error_explanation
      %h2= "#{pluralize(@example.errors.count, "error")} prohibited this example from being saved:"
      %ul
        - @example.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :video_link
    = f.text_field :video_link
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/examples/edit.html.haml
.row
  .large-12.columns
    %h1 Editing example

    = render 'form'

    = link_to 'Show', [@subtopic, @example]
    \|
    = link_to 'Back', subtopic_examples_path
    \|
    = link_to 'Destroy', [@subtopic, @example], :method => :delete, :data => { :confirm => 'Are you sure?' }    

app/views/examples/index.html.haml
.row
  .large-12.columns
    %h1 Listing examples

    %table
      %tr
        %th Name
        %th Video link
        %th Content
        %th
        %th
        %th

      - @examples.each do |example|
        %tr
          %td= example.name
          %td= example.video_link
          %td.proof= raw example.content
          %td= link_to 'Show', [@subtopic,example]
          %td= link_to 'Edit', edit_subtopic_example_path(@subtopic, example)
          %td= link_to 'Destroy', [@subtopic, example], :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Example', new_subtopic_example_path

app/views/examples/new.html.haml
.row
  .large-12.columns
    %h1 New example

    = render 'form'

    = link_to 'Back', subtopic_examples_path

app/views/examples/show.html.haml
.row
  .large-12.columns
    %p#notice= notice
    %p
      %b Name:
      = @example.name
    %p
      %b Video:
      .center
        = raw YouTubeAddy.youtube_embed_url(@example.video_link,853,480)
    %p
      %b Content:
      .proof
        = raw @example.content
    = link_to 'Edit', edit_subtopic_example_path
    \|
    = link_to 'Back', subtopic_examples_path