config/routes.rb
Rails.application.routes.draw do

  root :to => "visitors#index"
  
  resources :subtopics do
    resources :examples
    resources :proofs    
  end

  resources :courses do
    resources :topics
  end

  devise_for :users
  resources :users
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @topics = @course.topics
  end


  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :university)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.haml
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @course.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :university
    = f.text_field :university     
  .field
    = f.label :description
    = render 'layouts/textbar'
    = f.text_area :description, :id => 'wysihtml5-textarea', :class => 'input_area'
  .actions
    = f.submit 'Save'

app/views/courses/edit.html.haml
.row
  .large-12.columns
    %h1 Editing course

    = render 'form'

    = link_to 'Show', @course
    \|
    = link_to 'Back', courses_path

app/views/courses/index.html.haml
.row
  .large-12.columns
    %h1 List of Courses

    %table
      %tr
        %th Name
        %th Description
        %th
        %th
        %th

      - @courses.each do |course|
        %tr
          %td= course.name
          %td= course.description
          %td= link_to 'Show', course
          %td= link_to 'Edit', edit_course_path(course)
          %td= link_to 'Destroy', course, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Course', new_course_path

app/views/courses/new.html.haml
.row
  .large-12.columns
    %h1 New course

    = render 'form'

    = link_to 'Back', courses_path

app/views/courses/show.html.haml
.row
  .large-8.columns
    .show-info
      .mid-title.thick
        = @course.name
        %br        
      .subt-title.thin= @course.university
      %br
      = raw @course.description


  .large-4.columns
    .show-info
      .admin-panel
        Admin Panel
        %p
          %b= link_to "Create Topic for this course", new_course_topic_path(@course)

        = link_to 'Edit Course Information', edit_course_path(@course)
        \|
        = link_to 'Back', courses_path    
        


.row
  .large-12.columns      
  %hr
    .center
      %br
      %b.sub-title Course Tree
      

    %br
    -@topics.each do |topic|
      .topic-bar
        %b= topic.name
        %br
      - topic.subtopics.each do |subtopic|
        .subtopic-box
          %b=link_to subtopic.name, subtopic
        %br
        .row
          .large-6.columns
            %b.column-title Proofs
            %br
            -subtopic.proofs.each do |proof|
              .exercise-box
                = link_to proof.name, [subtopic, proof]
              %br
          .large-6.columns
            %b.column-title Examples
            %br
            -subtopic.examples.each do |example|
              .exercise-box
                =link_to example.name, [subtopic, example]
              %br